language: java
jdk: oraclejdk7

notifications:
  email: false

env:
  global:
    - ANDROID_SDK_VERSION="r22.0.5"
    - ANDROID_PLATFORM_TOOLS_VERSION="r18.0.1"

before_install:
  # Update a system for ia32 libraries
  # Just full upgrade of system and installing a ia32-libs not works
  # It's debian based system, /very/ stable version only
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi

  # Base android sdk setup
  - wget https://dl-ssl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export ANDROID_BUILD_TOOLS_HOME=${ANDROID_HOME}/build-tools/17.0.0
  - export PATH=${ANDROID_BUILD_TOOLS_HOME}:${ANDROID_HOME}/tools:${PATH}

  - export BASEDIR=`pwd`

  # We are should update Gradle, because Android Build Tools works with 1.6,
  # but on travis installed 1.4
  - wget http://downloads.gradle.org/distributions/gradle-1.6-all.zip
  - unzip -q -o gradle-1.6-all.zip
  - export PATH="${BASEDIR}/gradle-1.6/bin:${PATH}"

  # Let's try to build...
install: gradle build
script: gradle check